#!/bin/bash
# PekWM start file
# This file is a simple shell script; It gets run on pekwm startup, after 
# the theme and all config has loaded if it is set executable
# (chmod +x start).
#
# This is different from ~/.xinitrc because a normal configuration of 
# .xinitrc you'll run all commands, then launch the window manager last.
#
# It also gets re-run every time pekwm is restarted.
# 
# As for it's usefulness, well, it's up to you. I actually set my background
# from my start file; since it runs after the theme gets loaded, this 
# effectively overrides whatever's in the theme.
# 
# There's probably a few other good uses for it, too. I mainly pushed for it
# because when I was doing fluxbox's docs, people used to complain that there
# wasn't one, and I wanted to avoid that for pekwm. ;) --eyez

# Switch to the monitor if connected to the notebook
if (xrandr | grep "DP-1 connected"); then
	xrandr --output DP-1 --auto --output LVDS-1 --off
fi

if (xrandr | grep "VGA1 connected"); then
	xrandr --output VGA1 --auto --output LVDS-1 --off
fi


hsetroot -center ~/.pekwm/wallpapers/default.jpg &

# Slowdown the mouse
xset m 5/3 1 &

# Load settings for X tools, missing & at the end is correct
xrdb -merge ~/.Xdefaults

# Disable touchpad by default
synclient TouchpadOff=1

xterm &
yeahconsole &
xterm -title mc -e mc &

netwmpager &
xsysguard_biggray biggray/temp &
xscreensaver &

bin/keyboard_us_cz.sh &
xxkb &


kwrite &
icedove &
chromium &
#google-chrome &
pidgin &

# stalonetray &
# sleep 1 && nm-applet &
# sleep 3 && ~/bin/gui_reset.sh &
